"""esquema inicial do Atlas

Revision ID: a2e165918066
Revises: 
Create Date: 2026-08-06 15:56:21.067205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e165918066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuing_body', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('consulted_at', sa.DateTime(), nullable=True),
    sa.Column('effective_from', sa.String(length=20), nullable=True),
    sa.Column('effective_until', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['regulatory_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulatory_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulatory_documents_jurisdiction'), ['jurisdiction'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=30), nullable=True),
    sa.Column('address_complement', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city_ibge', sa.String(length=20), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('registry_number', sa.String(length=80), nullable=True),
    sa.Column('municipal_registration', sa.String(length=80), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_document', sa.String(length=50), nullable=True),
    sa.Column('contractor_name', sa.String(length=255), nullable=True),
    sa.Column('technical_responsible_name', sa.String(length=255), nullable=True),
    sa.Column('technical_responsible_registry', sa.String(length=80), nullable=True),
    sa.Column('use_type', sa.String(length=100), nullable=True),
    sa.Column('units_count', sa.Integer(), nullable=True),
    sa.Column('licensing_status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_city_ibge'), ['city_ibge'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('regulatory_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_key', sa.String(length=120), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('check', sa.JSON(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('manual_review_reason', sa.Text(), nullable=True),
    sa.Column('evidence_required', sa.JSON(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('source_document_label', sa.String(length=255), nullable=True),
    sa.Column('source_article', sa.String(length=120), nullable=True),
    sa.Column('effective_from', sa.String(length=20), nullable=True),
    sa.Column('effective_until', sa.String(length=20), nullable=True),
    sa.Column('validated_by_id', sa.String(), nullable=True),
    sa.Column('validated_by_name', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('catalog_version', sa.String(length=50), nullable=False),
    sa.Column('superseded_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['regulatory_documents.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['regulatory_rules.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulatory_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulatory_rules_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulatory_rules_rule_key'), ['rule_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulatory_rules_state'), ['state'], unique=False)

    op.create_table('daily_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('weather_condition', sa.String(length=50), nullable=False),
    sa.Column('manpower_own', sa.Integer(), nullable=False),
    sa.Column('manpower_subcontracted', sa.Integer(), nullable=False),
    sa.Column('activities_done', sa.Text(), nullable=False),
    sa.Column('occurrences', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_project_id'), ['project_id'], unique=False)

    op.create_table('eap_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['eap_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eap_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eap_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eap_items_project_id'), ['project_id'], unique=False)

    op.create_table('project_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('building_type', sa.String(length=100), nullable=False),
    sa.Column('lot_area', sa.Float(), nullable=True),
    sa.Column('built_area', sa.Float(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('front_setback', sa.Float(), nullable=True),
    sa.Column('side_setback', sa.Float(), nullable=True),
    sa.Column('rear_setback', sa.Float(), nullable=True),
    sa.Column('permeability_rate', sa.Float(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('is_official_baseline', sa.Boolean(), nullable=False),
    sa.Column('baseline_marked_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('change_origin', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_version_number')
    )
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_versions_project_id'), ['project_id'], unique=False)

    op.create_table('rule_validation_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['regulatory_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_validation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_validation_events_rule_id'), ['rule_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_version_id', sa.String(), nullable=True),
    sa.Column('project_version_number', sa.Integer(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('catalog_version', sa.String(length=50), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('conforme_count', sa.Integer(), nullable=False),
    sa.Column('nao_conforme_count', sa.Integer(), nullable=False),
    sa.Column('atencao_count', sa.Integer(), nullable=False),
    sa.Column('nao_verificavel_count', sa.Integer(), nullable=False),
    sa.Column('is_publishable', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('requested_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_project_version_id'), ['project_version_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_version_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_hash_sha256'), ['hash_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('protocol_processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_version_id', sa.String(), nullable=True),
    sa.Column('protocol_number', sa.String(length=120), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('process_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.String(length=20), nullable=True),
    sa.Column('decided_at', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_processes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_processes_project_id'), ['project_id'], unique=False)

    op.create_table('task_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('eap_item_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['eap_item_id'], ['eap_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_items_project_id'), ['project_id'], unique=False)

    op.create_table('protocol_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['protocol_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_events_process_id'), ['process_id'], unique=False)

    op.create_table('protocol_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('raised_at', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.String(length=20), nullable=True),
    sa.Column('linked_rule_key', sa.String(length=120), nullable=True),
    sa.Column('was_predicted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['protocol_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_requirements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_requirements_process_id'), ['process_id'], unique=False)

    op.create_table('validation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('analysis_run_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('rule_title', sa.String(length=255), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expected_value', sa.String(length=100), nullable=False),
    sa.Column('actual_value', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('rule_state', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_article', sa.String(length=120), nullable=True),
    sa.Column('source_citation', sa.String(length=255), nullable=True),
    sa.Column('source_is_verified', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.String(length=255), nullable=True),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('is_publishable', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_records_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_records_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_validation_records_analysis_run_id'))

    op.drop_table('validation_records')
    with op.batch_alter_table('protocol_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_requirements_process_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_requirements_organization_id'))

    op.drop_table('protocol_requirements')
    with op.batch_alter_table('protocol_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_events_process_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_events_organization_id'))

    op.drop_table('protocol_events')
    with op.batch_alter_table('task_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_items_organization_id'))

    op.drop_table('task_items')
    with op.batch_alter_table('protocol_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_processes_project_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_processes_organization_id'))

    op.drop_table('protocol_processes')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_hash_sha256'))

    op.drop_table('documents')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_project_version_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_organization_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('rule_validation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_validation_events_rule_id'))

    op.drop_table('rule_validation_events')
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_versions_organization_id'))

    op.drop_table('project_versions')
    with op.batch_alter_table('eap_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eap_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_eap_items_organization_id'))

    op.drop_table('eap_items')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_organization_id'))

    op.drop_table('daily_logs')
    with op.batch_alter_table('regulatory_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulatory_rules_state'))
        batch_op.drop_index(batch_op.f('ix_regulatory_rules_rule_key'))
        batch_op.drop_index(batch_op.f('ix_regulatory_rules_jurisdiction'))

    op.drop_table('regulatory_rules')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_index(batch_op.f('ix_projects_city_ibge'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('regulatory_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulatory_documents_jurisdiction'))

    op.drop_table('regulatory_documents')
    op.drop_table('organizations')
    # ### end Alembic commands ###
